dtype: fp16
bs: 2
seed: 42

memory: { }

prepare:
  # load base sd model
  - _target_: hcpdiff.workflow.LoadModelsAction
    pretrained_model: 'ckpts/MeinaMix_V11'
    dtype: ${dtype}
    scheduler:
      _target_: diffusers.DPMSolverMultistepScheduler # change Sampler
      beta_start: 0.00085
      beta_end: 0.012
      beta_schedule: 'scaled_linear'
      algorithm_type: 'dpmsolver++'
      use_karras_sigmas: True

  # build plugin (lokr)
  - _target_: hcpdiff.workflow.BuildPluginAction
    #cfg: 'cfgs/plugins/lokr.yaml'
    cfg:
      plugin_unet:
        lokr:
          _target_: lycoris.hcp.LokrBlock.wrap_model
          _partial_: True
          lr: 1e-4
          dim: 10000
          alpha: 0
          factor: 8
          layers:
            - 're:.*\.attn.?$'
            - 're:.*\.ff$'

      plugin_TE:
        lokr:
          _target_: lycoris.hcp.LokrBlock.wrap_model
          _partial_: True
          lr: 1e-4
          dim: 10000
          alpha: 0
          factor: 8
          layers:
            - 're:.*self_attn$'
            - 're:.*mlp$'

  - _target_: hcpdiff.workflow.BuildModelLoaderAction

  # load plugin ckpts (lokr)
  - _target_: hcpdiff.workflow.LoadPluginAction
    model: TE
    cfg:
      lokr:
        path: 'ckpts/tohsaka_rin-lokr/text_encoder-lokr-8000.safetensors'
  - _target_: hcpdiff.workflow.LoadPluginAction
    model: unet
    cfg:
      lokr:
        path: 'ckpts/tohsaka_rin-lokr/unet-lokr-8000.safetensors'

  # prepare model; optimize speed and VRAM
  - _target_: hcpdiff.workflow.XformersEnableAction
  - _target_: hcpdiff.workflow.ExecAction
    prog: |-
      from hcpdiff.utils.net_utils import to_cpu, to_cuda
      to_cuda(memory.unet)
      to_cuda(memory.vae)
  - _target_: hcpdiff.workflow.PrepareDiffusionAction
    dtype: ${dtype}
  - _target_: hcpdiff.workflow.VaeOptimizeAction
    slicing: True

actions:
  - _target_: hcpdiff.workflow.TextHookAction
    N_repeats: 1
    layer_skip: 1
  # encode text
  - _target_: hcpdiff.workflow.AttnMultTextEncodeAction
    prompt: 'masterpiece, best quality, tohsaka_rin_fatestaynightufotable, 1girl, outside'
    negative_prompt: 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
    bs: ${bs}
  # prepare seed
  - _target_: hcpdiff.workflow.SeedAction
    seed: ${seed}
  - _target_: hcpdiff.workflow.MakeTimestepsAction
    N_steps: 30
  # text to image
  - _target_: hcpdiff.workflow.MakeLatentAction
    width: 512
    height: 512
  - _target_: hcpdiff.workflow.LoopAction
    loop_value:
      timesteps: t #迭代timesteps，每一步的存成t到states里
    actions:
      - _target_: hcpdiff.workflow.DiffusionStepAction
        guidance_scale: 7.0
  # decode to image
  - _target_: hcpdiff.workflow.DecodeAction
    vae: ${hcp.from_memory:vae}
  - _target_: hcpdiff.workflow.SaveImageAction
    save_root: output_pipe/
    image_type: png