_base_:
  - cfgs/train/dataset/base_dataset.yaml
  - cfgs/train/train_base.yaml
  - cfgs/train/tuning_base.yaml


# 这部分根据需要改

train:
  save_step: 100

model:
  pretrained_model_name_or_path: 'runwayml/stable-diffusion-v1-5'
  lr_unet: 1e-4
  lr_text_encoder: 1e-5
  lora_rank: 8

data_cfg:
  batch_size: 4
  img_root: 'imgs/' # 数据集路径
  caption_file: 'imgs/' # 标注文件或文件夹
  target_area: 512*512 # 训练预期分辨率

object_name: pt-cat1 # lora训练的物体名(触发词)




# 这部分不用动

lora_unet:
  -
    lr: ${model.lr_unet}
    rank: ${model.lora_rank}
    layers:
      - 're:.*\.attn.?$'
      - 're:.*\.ff$'

lora_text_encoder:
  - lr: ${model.lr_text_encoder}
    rank: ${model.lora_rank}
    layers:
      - 're:.*self_attn$'
      - 're:.*mlp$'

data:
  dataset1:
    batch_size: ${data_cfg.batch_size}
    cache_latents: True

    source:
      data_source1:
        img_root: ${data_cfg.img_root}
        prompt_template: 'prompt_tuning_template/object.txt'
        caption_file: ${data_cfg.caption_file}

        word_names:
          pt1: ${object_name}

    bucket:
      _target_: hcpdiff.data.bucket.RatioBucket.from_files # aspect ratio bucket
      target_area: ${hcp.eval:"${data_cfg.target_area}"}
      num_bucket: 3