_base_:
  - cfgs/train/examples/fine-tuning.yaml

mixed_precision: 'bf16'

train:
  optimizer:
    _target_: transformers.optimization.Adafactor
    _partial_: True
    relative_step: False
    weight_decay: 1e-3

model:
  pretrained_model_name_or_path: 'stabilityai/stable-diffusion-xl-base-1.0'
  clip_skip: 1
  clip_final_norm: False
  force_cast_precision: True

data:
  dataset1:
    _target_: hcpdiff.data.CropInfoPairDataset
    batch_size: 4

    source:
      data_source1:
        img_root: 'imgs/'
        prompt_template: 'prompt_tuning_template/object.txt'
        caption_file: 'imgs/image_captions.json' # path to image captions (file_words)

    bucket:
      _target_: hcpdiff.data.bucket.RatioBucket.from_files # aspect ratio bucket
      target_area: ${hcp.eval:"1024*1024"}
      num_bucket: 4