_base_: [cfgs/train/examples/lora_conventional.yaml]

lora_unet:
  - # Linear
    lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.attn.?$'
      - 're:.*\.ff$'
  - # Conv2d
    lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.resnets$'
      - 're:.*\.proj_in$'
      - 're:.*\.proj_out$'
      - 're:.*\.conv$'

lora_text_encoder:
  - lr: 1e-5
    rank: 4
    layers:
      - 're:.*self_attn$'
      - 're:.*mlp$'