_base_: [ cfgs/infer/text2img_sdxl.yaml ]

pretrained_model: 'KBlueLeaf/kohaku-xl-beta7.1'  # base model created by kohaku
prompt: 'masterpiece, best quality, 1girl, solo, tohsaka rin'  # image of 远坂凛(tohsaka rin)
neg_prompt: 'bad anatomy, disembodied limb, realistic, blurry, watercolor'

clip_skip: 1 #动漫模型通常会跳过一个CLIP层

infer_args:
  width: 1024
  height: 1536  # image size
  guidance_scale: 7.5  # scale, when higher, the images will tend to be more similar
  num_inference_steps: 30  # how many steps

new_components:
  scheduler: # DPM++ 2M Karras
    _target_: diffusers.DPMSolverMultistepScheduler
    beta_start: 0.00085
    beta_end: 0.012
    algorithm_type: dpmsolver++
    beta_schedule: scaled_linear
    use_karras_sigmas: true
  vae: # use sdxl-base-v1.0's vae
    _target_: diffusers.AutoencoderKL.from_pretrained
    pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0  # path to vae model
    subfolder: vae
