_base_: [cfgs/infer/text2img.yaml]

ex_input:
  cond:
    _target_: hcpdiff.data.data_processor.ControlNetProcessor
    image: 'cond_img.png'

merge:
  plugin_cfg: cfgs/plugins/plugin_controlnet.yaml

  group1:
    type: 'unet'
    base_model_alpha: 1.0 # base model weight to merge with lora or part
    lora: null
    part: null
    plugin:
      controlnet1:
        path: 'ckpts/controlnet.ckpt'
        layers: 'all'