dtype: fp16
bs: 1
seed:
  - 42
  - 42
  - 42
  - 42

pretrained_model: 'Meina/MeinaMix_V11'
prompt:
  - 'masterpiece, best quality, 1girl, solo, {ling_arknights-5000:1.2}, blue_hair, horns, long_hair, pointy_ears, dragon_horns, blue_eyes, jewelry, earrings, smile, bangs, breasts, multicolored_hair, very_long_hair, braid, necktie, yellow_necktie, large_breasts, parted_lips, streaked_hair'
  - 'best quality, masterpiece, highres, solo, {ling_arknights-5000:1.15}, blue_hair, horns, long_hair, pointy_ears, dragon_horns, blue_eyes, jewelry, earrings, smile, bangs, breasts, multicolored_hair, very_long_hair, braid, necktie, yellow_necktie, large_breasts, parted_lips, streaked_hair, 1girl, black_gloves, black_shorts, boots, coat, dragon_girl, elbow_gloves, gloves, holding, looking_at_viewer, open_clothes, open_coat, shirt, short_shorts, shorts, thigh_strap, white_coat, white_footwear, white_shirt, bare_legs, dragon_tail, full_body, gourd, holding_staff, lantern, long_sleeves, staff, ankle_boots, closed_mouth, one_eye_closed, simple_background, wide_sleeves'
  - 'best quality, masterpiece, highres, solo, {night:1.10}, {starry sky:1.10}, beach, beautiful detailed sky, {extremely detailed background:1.20}, {ling_arknights-5000:0.8}, {standing:1.10}, looking at viewer, {bikini:1.30}, blue_hair, horns, long_hair, pointy_ears, dragon_horns, blue_eyes, jewelry, earrings, smile, bangs, breasts, multicolored_hair, very_long_hair, braid, necktie, yellow_necktie, large_breasts, parted_lips, streaked_hair, light smile'
  - 'best quality, masterpiece, highres, solo, {black business suit:1.40}, {tie:1.20}, {sunglasses:1.25}, {white gloves:1.15}, {white shirt:1.10}, {black skirt:1.15}, {smoking:1.20}, handsome, {ling_arknights-5000:1.15}, blue_hair, horns, long_hair, pointy_ears, dragon_horns, blue_eyes, jewelry, earrings, smile, bangs, breasts, multicolored_hair, very_long_hair, braid, necktie, yellow_necktie, large_breasts, parted_lips, streaked_hair'
neg_prompt:
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
N_repeats: 3

clip_skip: 1 #动漫模型通常会跳过一个CLIP层
models_dir: exps/ling_t4_r1_w1_p0.3_init_scunet_dp/ckpts
emb_dir: ${models_dir}

infer_args:
  width: 512
  height: 768  # image size
  guidance_scale: 7.5  # scale, when higher, the images will tend to be more similar
  num_inference_steps: 30  # how many steps

output_dir: 'output/'
lora:
  alpha: 0.8
  mask: [ 0.5, 1 ]
  dir: ${models_dir}
  step: 5000
  text_encoder: ${lora.dir}/text_encoder-${lora.step}.safetensors
  unet: ${lora.dir}/unet-${lora.step}.safetensors

memory: { }

prepare:
  - _target_: hcpdiff.workflow.LoadModelsAction
    pretrained_model: ${pretrained_model}
    dtype: ${dtype}
    scheduler: # DPM++ 2M Karras
      _target_: diffusers.DPMSolverMultistepScheduler
      beta_start: 0.00085
      beta_end: 0.012
      algorithm_type: dpmsolver++
      beta_schedule: scaled_linear
      use_karras_sigmas: true
    vae: # use NAI's vae
      _target_: diffusers.AutoencoderKL.from_pretrained
      pretrained_model_name_or_path: deepghs/animefull-latest  # path to vae model
      subfolder: vae
  - _target_: hcpdiff.workflow.BuildModelLoaderAction

  # load lora
  - _target_: hcpdiff.workflow.LoadLoraAction
    model: 'TE'
    cfg:
      - path: ${lora.text_encoder}
        alpha: ${lora.alpha}
        mask: ${lora.mask}
  - _target_: hcpdiff.workflow.LoadLoraAction
    model: 'unet'
    cfg:
      - path: ${lora.unet}
        alpha: ${lora.alpha}
        mask: ${lora.mask}
  - _target_: hcpdiff.workflow.XformersEnableAction
  - _target_: hcpdiff.workflow.ExecAction
    prog: |-
      from hcpdiff.utils.net_utils import to_cpu, to_cuda
      to_cuda(memory.unet)
      to_cuda(memory.text_encoder)
      to_cuda(memory.vae)
  - _target_: hcpdiff.workflow.PrepareDiffusionAction
    dtype: ${dtype}
  - _target_: hcpdiff.workflow.VaeOptimizeAction
    slicing: True

actions:
  - _target_: hcpdiff.workflow.TextHookAction
    N_repeats: ${N_repeats}
    layer_skip: ${clip_skip}
    emb_dir: ${emb_dir}

  ## Text2Img
  # encode text
  - _target_: hcpdiff.workflow.AttnMultTextEncodeAction
    prompt: ${prompt}
    negative_prompt: ${neg_prompt}
    bs: ${bs}
  # prepare seed
  - _target_: hcpdiff.workflow.SeedAction
    seed: ${seed}
  - _target_: hcpdiff.workflow.MakeTimestepsAction
    N_steps: ${infer_args.num_inference_steps}
  # text to image
  - _target_: hcpdiff.workflow.MakeLatentAction
    width: ${infer_args.width}
    height: ${infer_args.height}
  - _target_: hcpdiff.workflow.LoopAction
    loop_value:
      timesteps: t #迭代timesteps，每一步的存成t到states里
    actions:
      - _target_: hcpdiff.workflow.DiffusionStepAction
        guidance_scale: ${infer_args.guidance_scale}

  # decode to image
  - _target_: hcpdiff.workflow.DecodeAction
    vae: ${hcp.from_memory:vae}
  - _target_: hcpdiff.workflow.SaveImageAction
    save_root: ${output_dir}
    image_type: png