dtype: fp16
bs: 1
seed:
  - null
  - null

pretrained_model: 'Meina/MeinaMix_V11'
prompt:
  - 'masterpiece, best quality, 1girl, solo, tohsaka rin'  # image of 远坂凛(tohsaka rin)
  - 'masterpiece, best quality, 1girl, solo, tohsaka rin, {red bikini:1.3}'  # image of 远坂凛(tohsaka rin)
neg_prompt:
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
  - 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry'
N_repeats: 1

clip_skip: 1 #动漫模型通常会跳过一个CLIP层

infer_args:
  width: 512
  height: 768  # image size
  guidance_scale: 7.5  # scale, when higher, the images will tend to be more similar
  num_inference_steps: 30  # how many steps

output_dir: 'output/'

memory: { }

prepare:
  - _target_: hcpdiff.workflow.LoadModelsAction
    pretrained_model: ${pretrained_model}
    dtype: ${dtype}
    scheduler: # DPM++ 2M Karras
      _target_: diffusers.DPMSolverMultistepScheduler
      beta_start: 0.00085
      beta_end: 0.012
      algorithm_type: dpmsolver++
      beta_schedule: scaled_linear
      use_karras_sigmas: true
    vae: # use NAI's vae
      _target_: diffusers.AutoencoderKL.from_pretrained
      pretrained_model_name_or_path: deepghs/animefull-latest  # path to vae model
      subfolder: vae
  - _target_: hcpdiff.workflow.XformersEnableAction
  - _target_: hcpdiff.workflow.ExecAction
    prog: |-
      from hcpdiff.utils.net_utils import to_cpu, to_cuda
      to_cuda(memory.unet)
      to_cuda(memory.text_encoder)
      to_cuda(memory.vae)
  - _target_: hcpdiff.workflow.PrepareDiffusionAction
    dtype: ${dtype}
  - _target_: hcpdiff.workflow.VaeOptimizeAction
    slicing: True

actions:
  - _target_: hcpdiff.workflow.TextHookAction
    N_repeats: ${N_repeats}
    layer_skip: ${clip_skip}

  ## Text2Img
  # encode text
  - _target_: hcpdiff.workflow.AttnMultTextEncodeAction
    prompt: ${prompt}
    negative_prompt: ${neg_prompt}
    bs: ${bs}
  # prepare seed
  - _target_: hcpdiff.workflow.SeedAction
    seed: ${seed}
  - _target_: hcpdiff.workflow.MakeTimestepsAction
    N_steps: ${infer_args.num_inference_steps}
  # text to image
  - _target_: hcpdiff.workflow.MakeLatentAction
    width: ${infer_args.width}
    height: ${infer_args.height}
  - _target_: hcpdiff.workflow.LoopAction
    loop_value:
      timesteps: t #迭代timesteps，每一步的存成t到states里
    actions:
      - _target_: hcpdiff.workflow.DiffusionStepAction
        guidance_scale: ${infer_args.guidance_scale}

  # decode to image
  - _target_: hcpdiff.workflow.DecodeAction
    vae: ${hcp.from_memory:vae}
  - _target_: hcpdiff.workflow.SaveImageAction
    save_root: ${output_dir}
    image_type: png